# Generated by Django 5.1.2 on 2024-10-29 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0004_customuser_emailverificationtoken_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverificationtoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='EmailVerificationToken',
        ),
    ]
