# Generated by Django 5.1.2 on 2024-11-07 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
